// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The CLI (migrate/generate/studio) always uses the unpooled connection — see the comment on
    // DIRECT_URL in .env for why. Falls back to DATABASE_URL so this still works before DIRECT_URL
    // is set (e.g. a fresh clone that hasn't split the two yet).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
